# This is a sample build configuration for Haskell.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: haskell:latest

pipelines:
  default:
    - parallel:
      - step:
          services:
            - postgres
          script: # Modify the commands below to build your repository.
            - PGHOST=localhost PGUSER=test_user stack --install-ghc test --fast
      # - step:
      #     services:
      #       - postgres
      #     script: # Modify the commands below to build your repository.
      #       - stack --stack-yaml ghc-8.6.5.yaml --install-ghc test --fast
      # - step:
      #     services:
      #       - postgres
      #     script: # Modify the commands below to build your repository.
      #       - stack --stack-yaml ghc-8.8.3.yaml --install-ghc test --fast

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_USER: 'test_user'
