name: Haskell-CI
on: [push]
jobs:
  linux:
    name: GHC-${{ matrix.ghc-version }}
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: 'test_user'
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      matrix:
        ghc-version: [9.2.4, 9.0.2, 8.6.5]
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          ghc-version: ${{ matrix.ghc-version }}
          stack-version: 'latest'
      - run: PGHOST=localhost PGUSER=test_user stack --stack-yaml ghc-${{ matrix.ghc-version }}.yaml --install-ghc test --fast --haddock
